-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 00:27:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ubuntu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ubuntu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ubuntu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ubuntu` ;

-- -----------------------------------------------------
-- Table `ubuntu`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`categoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`cliente` (
  `nome_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`enderecos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `cpf_cliente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cpf_cliente` (`cpf_cliente` ASC) VISIBLE,
  CONSTRAINT `enderecos_ibfk_1`
    FOREIGN KEY (`cpf_cliente`)
    REFERENCES `ubuntu`.`cliente` (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`compra` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data_hora_compra` DATE NOT NULL,
  `desconto_aplicado` FLOAT(100,1) NOT NULL,
  `forma_pagamento` VARCHAR(100) NOT NULL,
  `total_compra` DECIMAL(10,0) NOT NULL,
  `cpf_cliente` VARCHAR(20) NOT NULL,
  `codigo_enderecos` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `cpf_cliente` (`cpf_cliente` ASC) VISIBLE,
  INDEX `codigo_enderecos` (`codigo_enderecos` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`cpf_cliente`)
    REFERENCES `ubuntu`.`cliente` (`cpf`),
  CONSTRAINT `compra_ibfk_2`
    FOREIGN KEY (`codigo_enderecos`)
    REFERENCES `ubuntu`.`enderecos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`subcategoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `codigo_categoria` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_categoria` (`codigo_categoria` ASC) VISIBLE,
  CONSTRAINT `subcategoria_ibfk_1`
    FOREIGN KEY (`codigo_categoria`)
    REFERENCES `ubuntu`.`categoria` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`numeros_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`numeros_serie` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `numero_serie` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`produto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(100) NOT NULL,
  `fabricante` VARCHAR(100) NOT NULL,
  `preco_base` DECIMAL(10,0) NOT NULL,
  `qtd_disponivel` INT NOT NULL,
  `codigo_subcategoria` INT NOT NULL,
  `codigo_numeros_serie` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_subcategoria` (`codigo_subcategoria` ASC) VISIBLE,
  INDEX `codigo_numeros_serie` (`codigo_numeros_serie` ASC) VISIBLE,
  CONSTRAINT `produto_ibfk_1`
    FOREIGN KEY (`codigo_subcategoria`)
    REFERENCES `ubuntu`.`subcategoria` (`codigo`),
  CONSTRAINT `produto_ibfk_2`
    FOREIGN KEY (`codigo_numeros_serie`)
    REFERENCES `ubuntu`.`numeros_serie` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ubuntu`.`item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubuntu`.`item_compra` (
  `codigo` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  `codigo_compra` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigo_produto` (`codigo_produto` ASC) VISIBLE,
  INDEX `codigo_compra` (`codigo_compra` ASC) VISIBLE,
  CONSTRAINT `item_compra_ibfk_1`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `ubuntu`.`produto` (`codigo`),
  CONSTRAINT `item_compra_ibfk_2`
    FOREIGN KEY (`codigo_compra`)
    REFERENCES `ubuntu`.`compra` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
