services:
  backend:
    container_name: backend_loja
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  frontend:
    container_name: frontend_loja
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  db:
    container_name: db_loja
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql 
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    container_name: db_loja_gui
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - db
volumes:
  mysql_data:
  mysql_config:
  
  meu-sync:
    external: true